QUIZ_ROUTE = "quiz"
QUIZ_QUESTION_ROUTE = "quiz-question"
QUIZ_ANSWER_ROUTE = "quiz-answer"
QUIZ_CATEGORY_ROUTE = "quiz-category"
USER_ROUTE = "user"
DOMAIN_ROUTE = "domain"
TEST_ROUTE = "test"
API_ROUTE = "api"
